name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Installing Mint
        run: |
          wget --no-verbose -O mint https://mint-lang.s3-eu-west-1.amazonaws.com/mint-master-linux
          chmod +x ./mint
          sudo mv ./mint /usr/local/bin/mint
      - name: Installing Mint packages
        run: |
          mint install
      - name: Building Mint
        run: |
          mint build --skip-service-worker --relative
      - name: Publish Documentation on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
